version: "3.8"

services:
  app1:
    build: .
    ports:
      - "3001:3001"
    # volumes:
    #   - ./uploads:/app/public/uploads 
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    command: "npm run start -- --hostname 0.0.0.0 --port 3001"
    networks:
      - pet-networks

  app2:
    build: .
    ports:
      - "3002:3002"   # different host port to avoid conflict
    # volumes:
    #   - ./uploads:/app/public/uploads
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    command: "npm run start -- --hostname 0.0.0.0 --port 3002"
    networks:
      - pet-networks

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - pet-networks

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - monitor_net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor_net
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./monitor/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./monitor/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./monitor/grafana-dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitor_net
networks:
  pet-networks:
    name: pet_networks
  monitor_net:
    name: monitor_net